[phases.setup]
nixPkgs = ["python311", "gcc", "bash"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"]

[start]
cmd = "bash start.sh"

[variables]
PATH = "/opt/venv/bin:$PATH"
PYTHONPATH = "."
PYTHONUNBUFFERED = "1"
